package ru.crystals.set10.test.maincash;


import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import ru.crystals.set10.config.Config;
import ru.crystals.set10.pages.operday.cashes.MainCashManualDocPage;
import ru.crystals.set10.utils.DisinsectorTools;
import static ru.crystals.set10.pages.operday.cashes.MainCashManualDocPage.*;


/*
 * Создание автоматических документов Главной кассы
 */
@Test (groups= "retail")
public class MainCashAutoGeneratedDocsTest extends MainCashConfigTest {
	

	@DataProvider (name = "Documents")
	private Object[][] setUpData(){
		return new Object[][]{
				{DOC_TYPE_PKO_EXCHANGE_INCOME},
				{DOC_TYPE_RKO_EXCHANGE_WITHDRAWAL},
		};
	}
	
	@BeforeClass
	public void setup(){
		openMainDocsPage();
	}
	
	@Test
	public void getDocNumber(){
		log.info("Последний номер документа ПКО: " + docs.getLastDocNumber("ПКО"));
		log.info("Последний номер документa РКО: " + docs.getLastDocNumber("РКО"));
		log.info("Номер документа ДДС: " + docs.getLastDocNumber("ДДС"));
		log.info("Номер документа ПКО Выручка: " + docs.getLastDocNumber("ПКО Выручка"));
		log.info("Номер документа Акт КМ-7: " + docs.getLastDocNumber("Акт КМ-7"));
	}
	
	@Test(description = "SRTE-175. Автомтическое заполнение полей документов ПКО/РКО при создании (автор, дата и время создания, номер документа)",
			dataProvider = "Documents")
	public void testRKOAutoGeneratedFields(String doctype){
	}
	
}
