package ru.crystals.set10.test.maincash;

import java.util.Date;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import ru.crystals.set10.config.Config;
import ru.crystals.set10.pages.basic.LoginPage;
import ru.crystals.set10.pages.operday.cashes.CashesPage;
import ru.crystals.set10.pages.operday.cashes.MainCashDocsPage;
import ru.crystals.set10.pages.operday.cashes.MainCashManualDocPage;
import ru.crystals.set10.test.AbstractTest;
import ru.crystals.set10.utils.DisinsectorTools;
import static ru.crystals.set10.pages.operday.OperDayPage.CASHES;
import static ru.crystals.set10.pages.operday.cashes.CashesPage.LOCATOR_MAINCASH_TAB;
import static ru.crystals.set10.pages.operday.cashes.CashDocsAbstractPage.*;
import static ru.crystals.set10.pages.operday.cashes.MainCashManualDocPage.*;

//@Test (groups= "retail")
public class PKOTest extends AbstractTest {
	
	MainCashDocsPage docs;
	MainCashManualDocPage rko;
	int docsOnPage = 0;
	long dayOfset = -86400000L * 2;
	
	
	String headAccountant = "Главбухова О.А";
	String receivedBy = "Получилов И.И";
	String receivedFrom = "Вручалова Г.Г";
	
	
	//@Parameters({"dayOfset"})
	@BeforeClass
	public void setUp(/*String ofset*/){
		//dayOfset = Long.valueOf(ofset) * 86400000L;
		docs = new LoginPage(getDriver(), Config.RETAIL_URL)
		.openOperDay(Config.MANAGER, Config.MANAGER_PASSWORD)
		.navigatePage(CashesPage.class, CASHES)
		.openTab(MainCashDocsPage.class, LOCATOR_MAINCASH_TAB);
		
		docs.switchToTable(LOCATOR_DOCS);
	}
	
	@DataProvider (name = "PKO")
	public Object[][] setUpRKOData(){
		return new Object[][]{
				{DOC_TYPE_PKO_CASH_EXCESS},
				{DOC_TYPE_PKO_UNENCLOSURE_ENCASHMENT},
				{DOC_TYPE_PKO_UNENCLOSURE_FROM_COUNTERPARTS},
//				{DOC_TYPE_PKO_INCOME_FROM_OTHER_COUNTERPARTS},
//				{DOC_TYPE_PKO_INCOME_FROM_EMPLOYEES},
//				{DOC_TYPE_PKO_EXCHANGE_INCOME}
		};
	}
	
	@Test(description = "SRTE-175. Добавление нового документа Приходной кассовый ордер (ПКО) на вкладку \"Документы\" Главной кассы", 
			dataProvider = "PKO")
	public void testAddNewPKO(String docType){
		docsOnPage = docs.getDocCountOnPage();
		rko = docs.addDoc();
		log.info("Добавление документа ПКО: " + docType);
		/* из списка ПКО, РКО выбирается текстовое представление PKOtypes */
		docs = rko.selectDocType(docType)
			.setTextField(FIELD_DOC_SUM, DisinsectorTools.randomMoney(1000, ","))
			.setOperDayDate(FIELD_DATE_OPERDAY, DisinsectorTools.getDate("dd.MM.yy", new Date().getTime() + dayOfset))
			.setTextField(FIELD_HEAD_ACCOUNTANT, headAccountant)
			.setTextField(FIELD_PERSON_RECEIVED, receivedBy)
			.setTextField(FIELD_RECEIVED_FROM, receivedFrom)
			.saveChanges()
			.backToMainCash();
		Assert.assertEquals(docs.getDocCountOnPage(), docsOnPage + 1, "Документ РКО " + docType.toString() + " не добавился на вкладку главной кассы Документы");
		/* проверить увеличение баланса*/
		//Assert.assertEquals(docs.getDocCountOnPage(), docsOnPage + 1, "Документ РКО " + docType.toString() + " не добавился на вкладку главной кассы Документы");
	}
	
	
	
	//@Test(description = "SRTE-175. Автомтическое заполнение полей ПКО")
	public void testPKOAutoGeneratedFields(){
	}
	
	//@Test(description = "SRTE-175. Редактирование ПКО, изменение баланса")
	public void testEditPKO(){
	}
	
	//@Test(description = "SRTE-175. Удаление ПКО, изменение баланса")
	public void testDeletePKO(){
	}
	
	
	@Test(  enabled = false,
			description = "SRTE-175. Печать ПКО, сохранение полей и баланса в печатной форме")
	public void testPrintPKO(String pkoType){
		String docNumber = "0";
		String sum = DisinsectorTools.randomMoney(1000, ",");
				
		rko = docs.addDoc();
		log.info("Добавление документа ПКО: " + pkoType);
		rko.selectDocType(pkoType)
				.setTextField(FIELD_DOC_SUM, sum)
				.setOperDayDate(FIELD_DATE_OPERDAY, DisinsectorTools.getDate("dd.MM.yy", new Date().getTime() + dayOfset))
				.setTextField(FIELD_HEAD_ACCOUNTANT, headAccountant)
				.setTextField(FIELD_RECEIVED_FROM, receivedFrom)
				.setTextField(FIELD_PERSON_RECEIVED, receivedBy)
				.saveChanges();

		docs = rko.backToMainCash();
		
		
		
	}
	
	
	
	
	
	
}
